import type { Metadata } from "next";
// style
import { Quicksand } from "next/font/google";
import "@/scss/main.scss";

//

export const metadata: Metadata = {
  title: ``,
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand", // CSS o'zgaruvchi sifatida ishlatish uchun
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={`${quicksand.variable}`}>
        {children}
      </body>
    </html>
  );
}
